import os

configfile: "../config/config.json"

include: "rules/common.smk"
include: "rules/downloads.smk"
include: "rules/sno_literature_processing.smk"
include: "rules/sno_tgirt_seq_processing.smk"
include: "rules/sno_families.smk"

rule all:
    input:
        #df = expand('data/sno_literature_processing/{sno_fasta}_location_formated.tsv', **config),
        #dd = expand('data/references/tgirt_seq_output/{species}_expressed_snoRNAs.tsv', species=config['species_tgirt'])
        df = 'data/references/infernal/cd_rfam_filtered_tuning_set.tsv'


rule all_downloads:
    input:
        blat_installation_file = "data/blat_test.txt",
        genome = expand('data/references/genome_fa/{species}_genome.fa', **config)




